### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by zhangnaiqian** [RUB-SysSec/gadget_synthesis#2]
Dear author, when I tried to use synthesizer to generate the ROP chain for a '.dll' binary, encountered following error message: 

synthesizer.selection    | MainProcess       - INFO    : Selecting 100 from 3356 available gadgets (1 fixed)
Traceback (most recent call last):
  File "synthesizer.py", line 372, in <module>
    main_single_threaded([t.absolute() for t in args.targets], args.config_name, args.out_dir, args.verbose)
  File "synthesizer.py", line 336, in main_single_threaded
    results.append(run_config(conf, target_config, disas_settings, workdir, verbose))
  File "synthesizer.py", line 163, in run_config
    gadgets, loc_db = disassemble_and_rebase_gadgets(selected_gadget_addresses, target_config)
  File "/home/user/synthesis/gadget_synthesis/synthesizer/disasm.py", line 463, in disassemble_and_rebase_gadgets
    asm_gadget = disas_and_rebase_gadget(mdis, gadget.addr, target_config.load_address)
  File "/home/user/synthesis/gadget_synthesis/synthesizer/disasm.py", line 423, in disas_and_rebase_gadget
    asm_block = addr_to_asmblock(mdis, addr)
  File "/home/user/synthesis/gadget_synthesis/synthesizer/disasm.py", line 65, in addr_to_asmblock
    block: 'Optional[Union[AsmBlock, AsmBlockBad]]' = mdis.dis_block(addr)
  File "/home/user/synthesis/gadget_synthesis/lib/miasm/miasm/core/asmblock.py", line 1377, in dis_block
    current_block, _ = self._dis_block(offset)
  File "/home/user/synthesis/gadget_synthesis/lib/miasm/miasm/core/asmblock.py", line 1286, in _dis_block
    instr = self.arch.dis(self.bin_stream, self.attrib, offset)
  File "/home/user/synthesis/gadget_synthesis/lib/miasm/miasm/core/cpu.py", line 1176, in dis
    pre_dis_info, bs, mode, offset, prefix_len = cls.pre_dis(
  File "/home/user/synthesis/gadget_synthesis/lib/miasm/miasm/arch/x86/arch.py", line 725, in pre_dis
    c = v.getbytes(offset)
  File "/home/user/synthesis/gadget_synthesis/lib/miasm/miasm/core/bin_stream.py", line 74, in getbytes
    val = self._getbytes(start, l)
  File "/home/user/synthesis/gadget_synthesis/lib/miasm/miasm/core/bin_stream.py", line 263, in _getbytes
    return self.bin.virt.get(start, start + l)
  File "/home/user/synthesis/gadget_synthesis/lib/miasm/miasm/loader/pe_init.py", line 116, in get
    return self.parent.rva.get(rva_start, rva_stop)
  File "/home/user/synthesis/gadget_synthesis/lib/miasm/miasm/loader/pe_init.py", line 49, in get
    if rva_start < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'

The previous steps for extracting gadgets are all good, I got 'function_addrs.json' and 'gadgets.json' for this target binary in cache. 

Thank you!

**Comment by mu00d8** [comment]
Hi,

this appears to be a bug in [Miasm](https://github.com/cea-sec/miasm), which we use for disassembly. If you are lucky, you can ignore this bug by replacing the `addr_to_asmblock` function in `./synthesizer/disasm.py` by the following:
```
def addr_to_asmblock(mdis: Machine, addr: int) -> Optional[AsmBlock]:
    try:
        block: 'Optional[Union[AsmBlock, AsmBlockBad]]' = mdis.dis_block(addr)
        if isinstance(block, AsmBlock) and not isinstance(block, AsmBlockBad):
            return block
    except Exception as e:
        logger.error(f"Miasm raised exception: {str(e)}")
    return None
```
This will treat any gadget for which Miasm raises an exception as invalid and skip it. This workaround should help unless the bug occurs for all gadgets.

**Comment by zhangnaiqian** [comment]
It works well! Thank you very much for your help!
